--- #YAML:1.0
name:                MojoX-Automata
version:             0.01
abstract:            Call Mojo dispatchers in a finite automata manner
license:             perl
author:              
    - Viacheslav Tikhanovskii <vti@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Mojo:                          0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
